# Generated by Django 6.0.2 on 2026-03-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_document_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
